### PR TITLE
Deduplication

### PR DESCRIPTION
**Pull request by D0ugins**
Implements evidence deduplication and improves the parser.

Parsing switched to using htmlparser2. Much faster, handles links properly, and is probably simpler. Also added fullcite field.

De-duplication works as follows
- Split full card text into sentences, then remove all non letter characters. Currently just uses a regex which could be improved but works well enough.
- Look up each sentences in a redis database mapping hashes of sentences to the card where they occur
- Filter out matches that are just coincidences.
- Get parents of all the actual matches
- If no matches
  - Set card's parent to itself, and add itself to its child list
- If one unique parent
  - Set card's parent to matches parent, and add itself to parents child list
- In rare case of multiple unique parents
  - Pick parent with lowest id to be new parent
  - Loop through children of all other parents and set their parent to the new one
  - Update the parent's child list.
- Sync parent changes to database (not child lists)

Tested with all openev files (~5.5k files, ~450k cards, 3% and 10% of total respectively)
Around 56% of evidence was a duplicate of some other evidence, 61% excluding analytics
Redis db used 115MB of memory, and it took a bit over an hour. CPU usage was low throughout, so speed could be increased by doing more things in parallel or running multiple threads if needed.

Information about duplicates is stored by adding a parent field to each card. Cards whose parent is the same card are duplicates of each other. Cards with no duplicates have their parent as their own id.

Deduplicated data can be searched in solr with [collapsing](https://solr.apache.org/guide/6_6/collapse-and-expand-results.html) or [grouping](https://solr.apache.org/guide/6_6/result-grouping.html)
Deduplicated data can be searched in elasticsearch with [collapsing](https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html) or [terms aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html)

It would be nice to have cards that appear more often be ranked higher when searching. There are a few ways to do this that I can think of.

- Do a normal search then re rank the results client side taking into account duplicate count: Probably simplest but would cause issues with pagination
- Add a field to each card with how many duplicates it has: Would probably be possible to do directly in a solr/elasticsearch query, but would be expensive to keep all the counts correct
- Take bucket size into account from within the query: Ideal solution but I'm not sure if it is possible

TODO
- [x] Queue undeduplicated evidence from the database
- [x] Add some way to mitigate the effect of cards being combined due to broken headers, might be fine depending on how search is implemented but would be nice to fix
- [x] Make detection of cites better

### CODE REVIEW

**Review by D0ugins — COMMENTED** [review]
The reason I had them coupled was to prevent memory issues if adding files was faster than deduplication and the deduplication queue filled up with tons of tasks. It was a temporary fix to just wait for the queue to empty to add the next file. Either waiting till drain() to fetch the text or hashing the sentences before adding the task would probably be enough where even if the queue is very backed up its not a huge issue.

**Comment by arvind-balaji** [comment]
I'm not sure how I feel about passing `Promise.done` between modules via events. Ideally, every module should be decoupled from each other, with only passive communication via events. Refactored a bit so that deduplicator runs independently from the parser (`DedupTasks` are created by the deduplicator via the evidence id from the `onAddEvidence` event).

I've also added an `EvidenceBucket` entity to keep track of all related cards as well as the frequency.

I'm seeing a fair bit of false matches when running on Open Ev 2020. Here's a dump of the largest bucket where `gid = JDHTGJ0039` - https://pastebin.com/RQY2aN2p

> Add some way to mitigate the effect of cards being combined due to broken headers, might be fine depending on how search is implemented but would be nice to fix

Are these errors possibly related to this?

**Comment by D0ugins** [comment]
> Are these errors possibly related to this?

Probably. I ran with openev from all years and the top few buckets looked very similar to that. Looking at the cards in those buckets I found a cards with multiple cards combined to one.

One way I can think of mitigating is just ignore really long cards in case a whole file gets detected as one card. This does stop some but there are still a quite a few false matches. If a combined card is the first one added I can't think of a way of detecting that without going back through afterwards and looking at where the matches come from.

**Comment by Hellisotherpeople** [comment]
So, I'd like to add some notes about "duplicate detection" with evidence. 

I think that techniques involving drilling down and using some actual hand written logic make sense here - but ultimately I think that you should try combining this with techniques from the world of string distances. 

I'd recommend looking into the Jaccard distance metric, which, when applied to the words of a document, does a pretty damn good job of finding "near duplicates" up to a given threshold. I'd recommend not looking for duplicate sentences necessarily, but rather near matches of two documents to each other this way. 

e.g. like this: 
https://skeptric.com/jaccard-duplicates/

**Comment by D0ugins** [comment]
> I'd recommend looking into the Jaccard distance metric, which, when applied to the words of a document, does a pretty damn good job of finding "near duplicates" up to a given threshold. I'd recommend not looking for duplicate sentences necessarily, but rather near matches of two documents to each other this way.

First of all thanks for chiming in with some input, if you have any other ideas please fell free to share them.

The reason I don't think that traditional string distances would work that well for this use case is because they are $O(n^2)$ in the number of documents being de-duplicated. Adding a new card requires comparing it against every single existing document. With all of the files from openev and the wikis, there are around 4 million cards, which means trillions of comparisons. I am pretty sure just reading all of the text from the database each time would be to slow to finish in a reasonable amount of time.

Most traditional string distance algorithms also score relatively low for strings of very different lengths. If one card contains the first paragraph from an article, and another card contains the first 5, we want those to be detected as duplicates.

**Comment by arvind-balaji** [comment]
This looks great, merged!

**Pull request merged**
